// Script to generate SYMBOL_TO_SECTOR mapping from sp500-symbols.ts

const mapping = {
  // Technology - Mega Cap
  'AAPL': 'Electronic Technology', 'MSFT': 'Electronic Technology', 
  'GOOGL': 'Electronic Technology', 'GOOG': 'Electronic Technology',
  'AMZN': 'Electronic Technology', 'NVDA': 'Electronic Technology',
  'META': 'Electronic Technology', 'TSLA': 'Electronic Technology',
  'AVGO': 'Electronic Technology', 'ORCL': 'Electronic Technology',
  
  // Technology - Large Cap
  'CRM': 'Electronic Technology', 'ADBE': 'Electronic Technology',
  'AMD': 'Electronic Technology', 'CSCO': 'Electronic Technology',
  'ACN': 'Electronic Technology', 'IBM': 'Electronic Technology',
  'INTU': 'Electronic Technology', 'TXN': 'Electronic Technology',
  'QCOM': 'Electronic Technology', 'AMAT': 'Electronic Technology',
  'MU': 'Electronic Technology', 'INTC': 'Electronic Technology',
  'ADI': 'Electronic Technology', 'LRCX': 'Electronic Technology',
  'KLAC': 'Electronic Technology', 'SNPS': 'Electronic Technology',
  'CDNS': 'Electronic Technology', 'MCHP': 'Electronic Technology',
  'FTNT': 'Electronic Technology', 'ANSS': 'Electronic Technology',
  'ROP': 'Electronic Technology', 'FICO': 'Electronic Technology',
  'MPWR': 'Electronic Technology', 'APH': 'Electronic Technology',
  'ADSK': 'Electronic Technology', 'MSI': 'Electronic Technology',
  'KEYS': 'Electronic Technology', 'ZBRA': 'Electronic Technology',
  'GDDY': 'Electronic Technology', 'PTC': 'Electronic Technology',
  'TYL': 'Electronic Technology', 'TER': 'Electronic Technology',
  'TRMB': 'Electronic Technology', 'VRSN': 'Electronic Technology',
  'AKAM': 'Electronic Technology', 'JNPR': 'Electronic Technology',
  'FFIV': 'Electronic Technology', 'NTAP': 'Electronic Technology',
  'STX': 'Electronic Technology', 'WDC': 'Electronic Technology',
  'HPE': 'Electronic Technology', 'HPQ': 'Electronic Technology',
  'DELL': 'Electronic Technology', 'CTSH': 'Electronic Technology',
  'GLW': 'Electronic Technology', 'ANET': 'Electronic Technology',
  'PANW': 'Electronic Technology', 'CRWD': 'Electronic Technology',
  'NOW': 'Electronic Technology', 'WDAY': 'Electronic Technology',
  'TEAM': 'Electronic Technology', 'DDOG': 'Electronic Technology',
  'ZS': 'Electronic Technology', 'NET': 'Electronic Technology',
  'OKTA': 'Electronic Technology', 'SNOW': 'Electronic Technology',
  'MDB': 'Electronic Technology', 'PLTR': 'Electronic Technology',
  
  // Communications
  'NFLX': 'Communications', 'DIS': 'Communications', 'CMCSA': 'Communications',
  'VZ': 'Communications', 'T': 'Communications', 'TMUS': 'Communications',
  'CHTR': 'Communications', 'EA': 'Communications', 'TTWO': 'Communications',
  'LYV': 'Communications', 'NWSA': 'Communications', 'NWS': 'Communications',
  'FOXA': 'Communications', 'FOX': 'Communications', 'OMC': 'Communications',
  'IPG': 'Communications', 'MTCH': 'Communications', 'PARA': 'Communications',
  
  // Consumer Services/Discretionary
  'HD': 'Consumer Services', 'MCD': 'Consumer Services', 'NKE': 'Consumer Services',
  'LOW': 'Consumer Services', 'SBUX': 'Consumer Services', 'TJX': 'Consumer Services',
  'BKNG': 'Consumer Services', 'ABNB': 'Consumer Services', 'CMG': 'Consumer Services',
  'MAR': 'Consumer Services', 'HLT': 'Consumer Services', 'YUM': 'Consumer Services',
  'DHI': 'Consumer Services', 'LEN': 'Consumer Services', 'PHM': 'Consumer Services',
  'POOL': 'Consumer Services', 'ULTA': 'Consumer Services', 'DPZ': 'Consumer Services',
  'DRI': 'Consumer Services', 'HAS': 'Consumer Services', 'WHR': 'Consumer Services',
  'LVS': 'Consumer Services', 'WYNN': 'Consumer Services', 'MGM': 'Consumer Services',
  'CZR': 'Consumer Services', 'NCLH': 'Consumer Services', 'RCL': 'Consumer Services',
  'CCL': 'Consumer Services', 'HRB': 'Consumer Services', 'MHK': 'Consumer Services',
  'LEG': 'Consumer Services', 'EXPE': 'Consumer Services', 'TRVG': 'Consumer Services',
  
  // Retail Trade
  'ORLY': 'Retail Trade', 'AZO': 'Retail Trade', 'ROST': 'Retail Trade',
  'TSCO': 'Retail Trade', 'BBY': 'Retail Trade', 'EBAY': 'Retail Trade',
  'ETSY': 'Retail Trade', 'GPC': 'Retail Trade', 'LKQ': 'Retail Trade',
  'AAP': 'Retail Trade', 'RL': 'Retail Trade', 'TPR': 'Retail Trade',
  'GWW': 'Retail Trade', 'KR': 'Retail Trade', 'COST': 'Retail Trade',
  'WMT': 'Retail Trade', 'TGT': 'Retail Trade', 'DLTR': 'Retail Trade',
  'DG': 'Retail Trade', 'WBA': 'Retail Trade',
  
  // Consumer Non-Durables
  'PG': 'Consumer Non-Durables', 'KO': 'Consumer Non-Durables',
  'PEP': 'Consumer Non-Durables', 'PM': 'Consumer Non-Durables',
  'MO': 'Consumer Non-Durables', 'MDLZ': 'Consumer Non-Durables',
  'CL': 'Consumer Non-Durables', 'KMB': 'Consumer Non-Durables',
  'GIS': 'Consumer Non-Durables', 'KHC': 'Consumer Non-Durables',
  'HSY': 'Consumer Non-Durables', 'K': 'Consumer Non-Durables',
  'CAG': 'Consumer Non-Durables', 'SJM': 'Consumer Non-Durables',
  'CPB': 'Consumer Non-Durables', 'HRL': 'Consumer Non-Durables',
  'MKC': 'Consumer Non-Durables', 'CHD': 'Consumer Non-Durables',
  'CLX': 'Consumer Non-Durables', 'TSN': 'Consumer Non-Durables',
  'SYY': 'Consumer Non-Durables', 'TAP': 'Consumer Non-Durables', 
  'STZ': 'Consumer Non-Durables', 'BF.B': 'Consumer Non-Durables', 
  'MNST': 'Consumer Non-Durables', 'KDP': 'Consumer Non-Durables', 
  'EL': 'Consumer Non-Durables', 'ADM': 'Consumer Non-Durables', 
  'BG': 'Consumer Non-Durables', 'INGR': 'Consumer Non-Durables', 
  'CVS': 'Consumer Non-Durables',
  
  // Energy Minerals
  'XOM': 'Energy Minerals', 'CVX': 'Energy Minerals', 'COP': 'Energy Minerals',
  'SLB': 'Energy Minerals', 'EOG': 'Energy Minerals', 'MPC': 'Energy Minerals',
  'PSX': 'Energy Minerals', 'VLO': 'Energy Minerals', 'OXY': 'Energy Minerals',
  'WMB': 'Energy Minerals', 'KMI': 'Energy Minerals', 'HES': 'Energy Minerals',
  'HAL': 'Energy Minerals', 'BKR': 'Energy Minerals', 'FANG': 'Energy Minerals',
  'DVN': 'Energy Minerals', 'MRO': 'Energy Minerals', 'APA': 'Energy Minerals',
  'CTRA': 'Energy Minerals', 'OVV': 'Energy Minerals', 'EQT': 'Energy Minerals',
  'TRGP': 'Energy Minerals', 'OKE': 'Energy Minerals', 'LNG': 'Energy Minerals',
  'CHRD': 'Energy Minerals', 'FCX': 'Energy Minerals',
  
  // Finance
  'BRK.B': 'Finance', 'JPM': 'Finance', 'V': 'Finance', 'MA': 'Finance',
  'BAC': 'Finance', 'WFC': 'Finance', 'MS': 'Finance', 'GS': 'Finance',
  'SPGI': 'Finance', 'BLK': 'Finance', 'C': 'Finance', 'SCHW': 'Finance',
  'AXP': 'Finance', 'CB': 'Finance', 'PGR': 'Finance', 'MMC': 'Finance',
  'AON': 'Finance', 'ICE': 'Finance', 'CME': 'Finance', 'MCO': 'Finance',
  'USB': 'Finance', 'PNC': 'Finance', 'TFC': 'Finance', 'COF': 'Finance',
  'AIG': 'Finance', 'MET': 'Finance', 'PRU': 'Finance', 'AFL': 'Finance',
  'ALL': 'Finance', 'TRV': 'Finance', 'AJG': 'Finance', 'HIG': 'Finance',
  'CINF': 'Finance', 'WRB': 'Finance', 'L': 'Finance', 'GL': 'Finance',
  'BRO': 'Finance', 'RJF': 'Finance', 'NTRS': 'Finance', 'STT': 'Finance',
  'BK': 'Finance', 'CFG': 'Finance', 'HBAN': 'Finance', 'RF': 'Finance',
  'KEY': 'Finance', 'FITB': 'Finance', 'MTB': 'Finance', 'ZION': 'Finance',
  'WTW': 'Finance', 'MKTX': 'Finance', 'MSCI': 'Finance', 'FDS': 'Finance',
  'BEN': 'Finance', 'IVZ': 'Finance', 'TROW': 'Finance', 'JEF': 'Finance',
  'SF': 'Finance', 'CBOE': 'Finance', 'FI': 'Finance', 'AMP': 'Finance',
  'ALLY': 'Finance', 'DFS': 'Finance', 'SYF': 'Finance', 'NDAQ': 'Finance',
  'LPLA': 'Finance',
  
  // Health Technology
  'UNH': 'Health Technology', 'LLY': 'Health Technology', 'JNJ': 'Health Technology',
  'ABBV': 'Health Technology', 'MRK': 'Health Technology', 'TMO': 'Health Technology',
  'ABT': 'Health Technology', 'DHR': 'Health Technology', 'PFE': 'Health Technology',
  'AMGN': 'Health Technology', 'BMY': 'Health Technology', 'GILD': 'Health Technology',
  'VRTX': 'Health Technology', 'ELV': 'Health Technology', 'HUM': 'Health Technology',
  'ISRG': 'Health Technology', 'ZTS': 'Health Technology', 'BSX': 'Health Technology',
  'SYK': 'Health Technology', 'MDT': 'Health Technology', 'EW': 'Health Technology',
  'BDX': 'Health Technology', 'A': 'Health Technology', 'IDXX': 'Health Technology',
  'DXCM': 'Health Technology', 'RMD': 'Health Technology', 'ALGN': 'Health Technology',
  'PODD': 'Health Technology', 'HOLX': 'Health Technology', 'STE': 'Health Technology',
  'BAX': 'Health Technology', 'TFX': 'Health Technology', 'TECH': 'Health Technology',
  'GEHC': 'Health Technology', 'SOLV': 'Health Technology', 'MOH': 'Health Technology',
  'VTRS': 'Health Technology', 'OGN': 'Health Technology', 'ZBH': 'Health Technology',
  'BIIB': 'Health Technology', 'MRNA': 'Health Technology', 'ILMN': 'Health Technology',
  'EXAS': 'Health Technology', 'INCY': 'Health Technology', 'NBIX': 'Health Technology',
  'ALNY': 'Health Technology', 'JAZZ': 'Health Technology', 'UTHR': 'Health Technology',
  'RARE': 'Health Technology', 'IONS': 'Health Technology', 'BMRN': 'Health Technology',
  'SGEN': 'Health Technology', 'FOLD': 'Health Technology', 'BLUE': 'Health Technology',
  'RGNX': 'Health Technology', 'ARVN': 'Health Technology', 'ARWR': 'Health Technology',
  'FATE': 'Health Technology', 'SGMO': 'Health Technology', 'VCYT': 'Health Technology',
  'PKI': 'Health Technology', 'WST': 'Health Technology', 'WAT': 'Health Technology',
  'COR': 'Health Technology',
  
  // Health Services
  'MCK': 'Health Services', 'CAH': 'Health Services', 'IQV': 'Health Services',
  'HCA': 'Health Services', 'UHS': 'Health Services', 'DVA': 'Health Services',
  'HSIC': 'Health Services', 'CI': 'Health Services', 'LH': 'Health Services',
  'DGX': 'Health Services', 'CNC': 'Health Services', 'ABC': 'Health Services',
  
  // Producer Manufacturing
  'GE': 'Producer Manufacturing', 'CAT': 'Producer Manufacturing',
  'RTX': 'Producer Manufacturing', 'HON': 'Producer Manufacturing',
  'BA': 'Producer Manufacturing', 'LMT': 'Producer Manufacturing',
  'DE': 'Producer Manufacturing', 'GD': 'Producer Manufacturing',
  'NOC': 'Producer Manufacturing', 'ETN': 'Producer Manufacturing',
  'ITW': 'Producer Manufacturing', 'MMM': 'Producer Manufacturing',
  'EMR': 'Producer Manufacturing', 'TT': 'Producer Manufacturing',
  'PH': 'Producer Manufacturing', 'PCAR': 'Producer Manufacturing',
  'CMI': 'Producer Manufacturing', 'CARR': 'Producer Manufacturing',
  'OTIS': 'Producer Manufacturing', 'IR': 'Producer Manufacturing',
  'FAST': 'Producer Manufacturing', 'ROK': 'Producer Manufacturing',
  'DOV': 'Producer Manufacturing', 'XYL': 'Producer Manufacturing',
  'FTV': 'Producer Manufacturing', 'AME': 'Producer Manufacturing',
  'LDOS': 'Producer Manufacturing', 'SNA': 'Producer Manufacturing',
  'PNR': 'Producer Manufacturing', 'TXT': 'Producer Manufacturing',
  'ROL': 'Producer Manufacturing', 'AOS': 'Producer Manufacturing',
  'GNRC': 'Producer Manufacturing', 'PWR': 'Producer Manufacturing',
  'VMI': 'Producer Manufacturing', 'MLI': 'Producer Manufacturing',
  'ALLE': 'Producer Manufacturing', 'AXON': 'Producer Manufacturing',
  'HWM': 'Producer Manufacturing', 'MIDD': 'Producer Manufacturing',
  'NDSN': 'Producer Manufacturing', 'AIT': 'Producer Manufacturing',
  'RBC': 'Producer Manufacturing', 'CTAS': 'Producer Manufacturing',
  'APTV': 'Producer Manufacturing', 'BWA': 'Producer Manufacturing',
  'F': 'Producer Manufacturing', 'GM': 'Producer Manufacturing',
  'NVR': 'Producer Manufacturing', 'LEN': 'Producer Manufacturing',
  'DHI': 'Producer Manufacturing', 'JCI': 'Producer Manufacturing',
  'HII': 'Producer Manufacturing', 'FBHS': 'Producer Manufacturing',
  'LEG': 'Producer Manufacturing', 'MAS': 'Producer Manufacturing',
  
  // Transportation
  'UPS': 'Transportation', 'UNP': 'Transportation', 'CSX': 'Transportation',
  'NSC': 'Transportation', 'FDX': 'Transportation', 'DAL': 'Transportation',
  'UAL': 'Transportation', 'AAL': 'Transportation', 'LUV': 'Transportation',
  'ALK': 'Transportation', 'WAB': 'Transportation', 'ODFL': 'Transportation',
  'JBHT': 'Transportation', 'CHRW': 'Transportation', 'EXPD': 'Transportation',
  'IEX': 'Transportation',
  
  // Process Industries
  'LIN': 'Process Industries', 'APD': 'Process Industries', 'SHW': 'Process Industries',
  'ECL': 'Process Industries', 'CTVA': 'Process Industries', 'DD': 'Process Industries',
  'DOW': 'Process Industries', 'PPG': 'Process Industries', 'STLD': 'Process Industries',
  'ALB': 'Process Industries', 'CF': 'Process Industries', 'MOS': 'Process Industries',
  'FMC': 'Process Industries', 'IFF': 'Process Industries', 'EMN': 'Process Industries',
  'CE': 'Process Industries', 'BALL': 'Process Industries', 'AVY': 'Process Industries',
  'PKG': 'Process Industries', 'IP': 'Process Industries', 'AMCR': 'Process Industries',
  'SEE': 'Process Industries', 'WRK': 'Process Industries', 'CLF': 'Process Industries',
  'RS': 'Process Industries', 'LYB': 'Process Industries',
  
  // Commercial Services
  'AMT': 'Commercial Services', 'PLD': 'Commercial Services', 'EQIX': 'Commercial Services',
  'PSA': 'Commercial Services', 'WELL': 'Commercial Services', 'DLR': 'Commercial Services',
  'O': 'Commercial Services', 'SPG': 'Commercial Services', 'VICI': 'Commercial Services',
  'CBRE': 'Commercial Services', 'EXR': 'Commercial Services', 'IRM': 'Commercial Services',
  'AVB': 'Commercial Services', 'EQR': 'Commercial Services', 'VTR': 'Commercial Services',
  'SBAC': 'Commercial Services', 'WY': 'Commercial Services', 'INVH': 'Commercial Services',
  'MAA': 'Commercial Services', 'ESS': 'Commercial Services', 'UDR': 'Commercial Services',
  'ARE': 'Commercial Services', 'DOC': 'Commercial Services', 'CPT': 'Commercial Services',
  'HST': 'Commercial Services', 'REG': 'Commercial Services', 'BXP': 'Commercial Services',
  'FRT': 'Commercial Services', 'KIM': 'Commercial Services', 'VNO': 'Commercial Services',
  'SUI': 'Commercial Services', 'PEAK': 'Commercial Services', 'CCI': 'Commercial Services',
  'GLPI': 'Commercial Services', 'LAMR': 'Commercial Services', 'CPRT': 'Commercial Services',
  'J': 'Commercial Services', 'WM': 'Commercial Services', 'RSG': 'Commercial Services',
  'VRSK': 'Commercial Services', 'EFX': 'Commercial Services',
  'MCO': 'Commercial Services', 'MSCI': 'Commercial Services',
  'FDS': 'Commercial Services', 'INFO': 'Commercial Services', 'WU': 'Commercial Services',
  'FLT': 'Commercial Services', 'RHI': 'Commercial Services', 'NLSN': 'Commercial Services',
  
  // Non-Energy Minerals
  'NEM': 'Non-Energy Minerals', 'VMC': 'Non-Energy Minerals', 'MLM': 'Non-Energy Minerals',
  'NUE': 'Non-Energy Minerals',
  
  // Utilities
  'NEE': 'Utilities', 'SO': 'Utilities', 'DUK': 'Utilities', 'CEG': 'Utilities',
  'SRE': 'Utilities', 'AEP': 'Utilities', 'VST': 'Utilities', 'D': 'Utilities',
  'PCG': 'Utilities', 'PEG': 'Utilities', 'EXC': 'Utilities', 'XEL': 'Utilities',
  'ED': 'Utilities', 'WEC': 'Utilities', 'ES': 'Utilities', 'AWK': 'Utilities',
  'DTE': 'Utilities', 'PPL': 'Utilities', 'AEE': 'Utilities', 'CMS': 'Utilities',
  'EIX': 'Utilities', 'FE': 'Utilities', 'ETR': 'Utilities', 'CNP': 'Utilities',
  'NI': 'Utilities', 'LNT': 'Utilities', 'ATO': 'Utilities', 'EVRG': 'Utilities',
  'PNW': 'Utilities', 'NRG': 'Utilities', 'AES': 'Utilities',
  
  // Technology Services
  'PAYX': 'Technology Services', 'CDW': 'Technology Services', 'CDAY': 'Technology Services',
  'CERN': 'Technology Services', 'CRL': 'Technology Services', 'CTXS': 'Technology Services',
  'INTU': 'Technology Services', 'JKHY': 'Technology Services',
  'NLOK': 'Technology Services', 'PYPL': 'Technology Services',
  'TRMB': 'Technology Services', 'TYL': 'Technology Services', 'TWTR': 'Technology Services',
  'ANSS': 'Technology Services', 'SNPS': 'Technology Services',
  'CDNS': 'Technology Services', 'ADP': 'Technology Services', 'PAYC': 'Technology Services',
  'EPAM': 'Technology Services', 'MTCH': 'Technology Services',
  'FIS': 'Technology Services', 'FISV': 'Technology Services', 'ORCL': 'Technology Services',
  'GPN': 'Technology Services', 'CRM': 'Technology Services',
  'AKAM': 'Technology Services',
};

console.log(`Total symbols mapped: ${Object.keys(mapping).length}`);
console.log('Formatted for TypeScript:');
console.log(JSON.stringify(mapping, null, 2));
