// Complete S&P 500 Company Domain Mapping for Logo Extraction
// Used with Clearbit Logo API: https://logo.clearbit.com/{domain}
export const SP500_COMPANY_DOMAINS: { [key: string]: string } = {
  // Technology & Electronics (FAANG + Others)
  'NVDA': 'nvidia.com',
  'AAPL': 'apple.com',
  'MSFT': 'microsoft.com',
  'GOOGL': 'google.com',
  'GOOG': 'google.com',
  'AMZN': 'amazon.com',
  'META': 'meta.com',
  'NFLX': 'netflix.com',
  'INTC': 'intel.com',
  'AMD': 'amd.com',
  'CSCO': 'cisco.com',
  'ORCL': 'oracle.com',
  'CRM': 'salesforce.com',
  'PYPL': 'paypal.com',
  'ADBE': 'adobe.com',
  'AVGO': 'broadcom.com',
  'MU': 'micron.com',
  'QCOM': 'qualcomm.com',
  'ASML': 'asml.com',
  'MCHP': 'microchip.com',
  'SNPS': 'synopsys.com',
  'CDNS': 'cadence.com',
  'KLAC': 'kla.com',
  'LRCX': 'lam.com',
  'AMAT': 'appliedmaterials.com',
  'INTU': 'intuit.com',
  'SPLK': 'splunk.com',
  'CRWD': 'crowdstrike.com',
  'OKTA': 'okta.com',
  'ZOOM': 'zoom.us',
  'DASH': 'doordash.com',
  'ABNB': 'airbnb.com',
  'UBER': 'uber.com',
  'SPOT': 'spotify.com',
  'TTD': 'thetradedesk.com',
  'PLTR': 'palantir.com',
  'COIN': 'coinbase.com',
  'SQ': 'square.com',
  'SNOW': 'snowflake.com',
  'NET': 'cloudflare.com',
  'DDOG': 'datadoghq.com',
  'TEAM': 'atlassian.com',
  'DOCS': 'vistara.com', // Changed from docs.com
  'NOW': 'servicenow.com',
  'PSTG': 'postgresql.com',
  'DBX': 'dropbox.com',
  'BOX': 'box.com',
  'PINS': 'pinterest.com',
  'SNAP': 'snap.com',
  'TWTR': 'twitter.com',
  'ROKU': 'roku.com',
  'NTNX': 'nutanix.com',
  'RPD': 'rapidfilings.com',
  'VIST': 'vistara.com',
  'TRMB': 'trimble.com',
  'GPN': 'global-payments.com',
  'PCTY': 'paylocity.com',
  'VEEX': 'veeam.com',
  'FTNT': 'fortinet.com',
  'PANW': 'paloaltonetworks.com',
  'TENB': 'tenable.com',
  'CYBR': 'cyberark.com',
  'ZS': 'zscaler.com',
  'WDAY': 'workday.com',
  'CGNX': 'cognex.com',

  // Financial Services
  'JPM': 'jpmorganchase.com',
  'BAC': 'bankofamerica.com',
  'WFC': 'wellsfargo.com',
  'C': 'citigroup.com',
  'GS': 'goldmansachs.com',
  'MS': 'morganstanley.com',
  'BLK': 'blackrock.com',
  'AMP': 'ampf.com',
  'AXP': 'americanexpress.com',
  'BK': 'bankofnewyork.com',
  'USB': 'usbank.com',
  'PNC': 'pnc.com',
  'SCHW': 'schwab.com',
  'TROW': 'troweprice.com',
  'WMT': 'walmart.com',
  'PGR': 'progressive.com',
  'ICE': 'intercontinentalexchange.com',
  'CME': 'cmegroup.com',
  'CBOE': 'cboe.com',
  'LPLA': 'lpl.com',
  'BRK.B': 'berkshirehathaway.com',
  'V': 'visa.com',
  'MA': 'mastercard.com',
  'DFS': 'discover.com',
  'VICI': 'vici.com',
  'MGM': 'mgmresorts.com',
  'LVS': 'lvs.com',
  'WYNN': 'wynnresorts.com',
  'PENN': 'pennentertainment.com',
  'PARA': 'paramount.com',
  'FOXA': 'fox.com',
  'FOX': 'fox.com',

  // Healthcare & Pharmaceuticals
  'JNJ': 'jnj.com',
  'UNH': 'unitedhealth.com',
  'PFE': 'pfizer.com',
  'ABBV': 'abbvie.com',
  'LLY': 'lilly.com',
  'MRK': 'merck.com',
  'AMGN': 'amgen.com',
  'BMY': 'bmy.com',
  'GILD': 'gilead.com',
  'BIIB': 'biogen.com',
  'VRTX': 'vrtx.com',
  'REGN': 'regeneron.com',
  'ALXN': 'alexion.com',
  'XLRN': 'exelixis.com',
  'RARE': 'ultragenyx.com',
  'SRPT': 'sarepta.com',
  'TECH': 'techdata.com',
  'HCA': 'hcahealthcare.com',
  'UHS': 'uhsinc.com',
  'STE': 'steris.com',
  'BIO': 'biotechradar.com',
  'ANTM': 'antheminc.com',
  'CI': 'cigna.com',
  'HUM': 'humana.com',
  'CVS': 'cvs.com',
  'WBA': 'walgreensbootsalliance.com',
  'RCL': 'royalcaribbean.com',
  'CCL': 'carnivalcorp.com',
  'MAR': 'marriott.com',
  'IHG': 'ihgplc.com',
  'H': 'hyatthotels.com',
  'MHK': 'mohawkind.com',
  'PHM': 'pulte.com',
  'DHI': 'dhicorp.com',
  'LEN': 'lennar.com',
  'TOL': 'toll.com',
  'NVR': 'nvreinc.com',
  'BECN': 'beaconroofing.com',
  'LGIH': 'lgihomes.com',

  // Energy
  'XOM': 'exxonmobil.com',
  'CVX': 'chevron.com',
  'COP': 'conocophillips.com',
  'SLB': 'slb.com',
  'EOG': 'eogin.com',
  'MPC': 'marathonpetroleum.com',
  'PSX': 'phillipsexchange.com',
  'VLO': 'valero.com',
  'HES': 'hess.com',
  'FANG': 'diamondbackenergy.com',
  'MRO': 'marathonoil.com',
  'OXY': 'oxy.com',
  'APA': 'apacorp.com',
  'CNQ': 'canadian-natural.com',
  'CAJ': 'cabot.com',
  'CTRA': 'ctra.com',
  'DVN': 'devon.com',
  'ERF': 'energia.com',
  'KMI': 'kinder.com',
  'OKE': 'oneok.com',
  'MMP': 'magellan.com',
  'EPD': 'enterprise.com',
  'LNG': 'lng.com',
  'RIG': 'transocean.com',
  'SDRL': 'seadrill.com',
  'WLKP': 'whiting.com',
  'BKR': 'bakerhughes.com',

  // Consumer Discretionary
  'HD': 'homedepot.com',
  'MCD': 'mcdonalds.com',
  'LOW': 'lowes.com',
  'TJX': 'tjxcompanies.com',
  'DKS': 'dicks.com',
  'BBY': 'bestbuy.com',
  'GPS': 'gapinc.com',
  'NKE': 'nike.com',
  'LULU': 'lululemon.com',
  'AZO': 'autozone.com',
  'KSS': 'kohls.com',
  'ROST': 'rossstores.com',
  'FIVE': 'fivebelow.com',
  'RH': 'restoration-hardware.com',
  'COTY': 'coty.com',
  'EL': 'estee-lauder.com',
  'ULTA': 'ulta.com',
  'CPRI': 'capri.com',
  'TPH': 'tapestry.com',
  'LVMH': 'lvmh.com',
  'WWE': 'wwe.com',
  'DIS': 'disney.com',
  'CMG': 'chipotle.com',
  'SBUX': 'starbucks.com',
  'YUM': 'yum.com',
  'MKL': 'markel.com',
  'BF.B': 'brown-forman.com',
  'DXCM': 'dexcom.com',

  // Consumer Staples
  'COST': 'costco.com',
  'PG': 'pg.com',
  'KO': 'coca-cola.com',
  'PEP': 'pepsico.com',
  'MO': 'altria.com',
  'PM': 'philipmorris.com',
  'GIS': 'generalmills.com',
  'K': 'kellogg.com',
  'CAG': 'conagra.com',
  'TSN': 'tyson.com',
  'CHD': 'churchdwight.com',
  'CL': 'colgate-palmolive.com',
  'STZ': 'constellation.com',
  'SJM': 'smuckers.com',
  'MNST': 'monsterenergy.com',
  'BUD': 'budweiser.com',
  'DEO': 'diageo.com',
  'TAP': 'molson.com',
  'KMB': 'kimberly-clark.com',
  'EEM': 'isharesmcom',

  // Industrials & Manufacturing
  'BA': 'boeing.com',
  'CAT': 'caterpillar.com',
  'GE': 'ge.com',
  'MMM': '3m.com',
  'HON': 'honeywell.com',
  'RTX': 'rtx.com',
  'LMT': 'lockheedmartin.com',
  'NOC': 'northropgrumman.com',
  'GD': 'generalsdynamics.com',
  'TRI': 'trican.com',
  'EMR': 'emerson.com',
  'ETN': 'eaton.com',
  'PWR': 'quanta.com',
  'IEX': 'idexcorp.com',
  'PCAR': 'paccar.com',
  'GWW': 'graingercom',
  'SPY': 'spdr.com',
  'FAST': 'fastenal.com',
  'TT': 'textron.com',
  'UTX': 'utx.com',
  'FSI': 'fallonspeedway.com',
  'GLW': 'corning.com',
  'IR': 'ingressrobotics.com',
  'EXPD': 'expeditors.com',
  'FDX': 'fedex.com',
  'UPS': 'ups.com',
  'ODFL': 'olddominionfreight.com',
  'ALK': 'alaskaair.com',
  'DAL': 'delta.com',
  'AAL': 'aa.com',
  'UAL': 'united.com',
  'LUV': 'southwest.com',

  // Utilities
  'NEE': 'nexteraenergy.com',
  'DUK': 'duke-energy.com',
  'SO': 'southernco.com',
  'EXC': 'exeloncom',
  'XEL': 'xcel.com',
  'EIX': 'eix.com',
  'WEC': 'wecenergy.com',
  'AES': 'aesglobal.com',
  'ES': 'evergyscom',
  'FE': 'firstenergy.com',
  'PPL': 'pplcorp.com',
  'AEP': 'aep.com',
  'PEG': 'pepco.com',
  'CMS': 'consumersenergy.com',
  'DTE': 'dteenergy.com',
  'ED': 'coned.com',
  'XRX': 'xerox.com',

  // Real Estate Investment Trusts (REITs)
  'AMT': 'americantower.com',
  'PLD': 'prologis.com',
  'CCI': 'crowncastle.com',
  'EQIX': 'equinix.com',
  'DLR': 'digitalrealty.com',
  'PSA': 'publicstorage.com',
  'AVB': 'avalonbay.com',
  'EQR': 'equityresidential.com',
  'MAA': 'maacorp.com',
  'ARE': 'alexandria.com',
  'ESS': 'essexreit.com',
  'VTR': 'ventas.com',
  'WRY': 'welltowerinc.com',
  'OHI': 'ohireit.com',
  'LTC': 'ltcreit.com',
  'CUBE': 'cubesmartinc.com',
  'EGP': 'eigengroup.com',
  'KIM': 'kimcorealty.com',
  'UE': 'urbanecom',
  'NSA': 'nsagreit.com',
  'SLG': 'slgreen.com',
  'RXO': 'rxo.com',

  // Materials & Chemicals
  'LYB': 'lyondell.com',
  'FCX': 'freeportmcmoran.com',
  'DOW': 'dow.com',
  'DD': 'dupont.com',
  'SHW': 'sherwin-williams.com',
  'APD': 'airproducts.com',
  'NEM': 'newmont.com',
  'GLD': 'spdrgoletrust.com',
  'SCCO': 'southerncopper.com',
  'MT': 'arcellormittal.com',
  'NUE': 'nucor.com',
  'X': 'uss.com',
  'CLF': 'clevelandcliffs.com',
  'ALB': 'albemarle.com',
  'CARG': 'cargurus.com',
  'MOS': 'mosaic.com',
  'CF': 'cfind.com',
  'ATI': 'alleghenytech.com',
  'WWW': 'wwacom',
  'CTVA': 'corteva.com',
  'ADM': 'adm.com',

  // Communications & Media
  'VZ': 'verizon.com',
  'T': 'attcom',
  'CHTR': 'charter.com',
  'CMCSA': 'comcast.com',
  'TMUS': 'tmobile.com',
  'S': 'sprint.com',
  'IPG': 'interpublic.com',
  'OMCL': 'omnicom.com',
  'DISCA': 'discovery.com',
  'DISCK': 'discovery.com',
  'DISCB': 'discovery.com',

  // Healthcare Services & Equipment
  'ILMN': 'illumina.com',
  'VEEV': 'veeva.com',
  'INMD': 'inmode.com',
  'MRNA': 'modernatx.com',
  'BNTX': 'biontech.com',
  'ADTRW': 'adatatherap.com',
};

// Get company domain for logo lookup
export function getCompanyDomain(ticker: string): string {
  return SP500_COMPANY_DOMAINS[ticker] || `${ticker.toLowerCase()}.com`;
}

// Get logo URL using Yahoo Finance CDN (most reliable for stock logos)
export function getCompanyLogoUrl(ticker: string): string {
  // Use Yahoo Finance logo CDN - most reliable source for stock company logos
  return `https://s.yimg.com/no/Q/Images/logos/2022/${ticker}.png`;
}

